remote_theme: "mmistakes/minimal-mistakes@4.19.3"

minimal_mistakes_skin: "sunrise"

# Plugins
plugins:
  - jekyll-include-cache

title: granolarr
description: >- # this means to ignore newlines until "baseurl:"
  geog**GR**aphic d**A**ta scie**N**ce, repr**O**ducib**L**e te**A**ching resou**R**ce in **R**
search: true

include:
  - _pages

author: Stefano De Sabbata

footer:
  links:
    - label: "Website"
      icon: "fas fa-link"
      url: "https://https://twitter.com/maps4thought"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sdesabbata/granolarr"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-156463146-1"
    anonymize_ip: false # default